# Generated by Django 5.0.7 on 2024-07-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Japanese_Hiragana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherLang', models.CharField(max_length=120)),
                ('english', models.CharField(max_length=120)),
                ('langFamily', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120)),
            ],
        ),
    ]
